
export enum RoomStatusEnum {
    LIBRE = 'Libre',
    PREPARADA = 'Preparada',
    SUCIA = 'Sucia',
    MEDIA_SUCIA = 'Media Sucia',
    RESERVADA = 'Reservada',
    RESERVADA_PREPARADA = 'Reservada/Preparada',
    EN_LIMPIEZA = 'En limpieza',
    OCUPADA = 'Ocupada',
    EN_SUPERVISION  = 'En supervisión',
    POR_COBRAR = 'Ocupada por cobrar',
    ROOM_SERVICE = 'Ocupada room service',
    BLOQUEADA = 'Bloqueada',
    LIBRE_CON_DETALLES = 'Con Detalles',
    ROOM_SERVICE_POR_COBRAR = 'Ocupada room service por cobrar',
    ROOM_SERVICE_EXTRAS_POR_COBRAR = 'Ocupada room service extras por cobrar',
    MANTENIMIENTO = 'Mantenimiento',
    SUPERVISION_MANTENIMIENTO = 'Supervision de Mantenimiento',
}
