query getAllRooms {
 habitaciones {
      id
      numeroHabitacion
      piso
      estadoHabitacion {
        nombre
      }
    }
}

  query Habitacion($num:String!){
  habitacion(id_o_numero: $num) {
    id
    numeroHabitacion
    tipoHabitacion {
      id
      nombre
    }
  }
}

query Tarifas {
  tarifas{
  nombre
  id
  costoHabitacion
  costoHoraExtra
  costoHospedajeExtra
  costoPersonaExtra
  horasExtraMax
  hospedajesExtraMax
  personasExtraMax
  tipoHabitacion {
    nombre
  }
  }
}
